name: quran_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  logger: ^0.7.0+2
  rxdart: ^0.23.1
  rx_command: ^5.0.2
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  material_design_icons_flutter: ^3.0.3289
  intl: ^0.16.0
  font_awesome_flutter: ^8.2.0
  bubble_tab_indicator: ^0.1.4
  built_collection: ^4.3.2
  built_value: ^7.0.2
  shimmer: ^1.0.1
  flutter_widgets: ^0.1.11
  xml2json: ^4.1.1
  tuple: ^1.0.3
  rx_shared_preferences: ^1.1.1+1
  expandable: ^4.1.2
  sqflite: ^1.2.1
  path_provider: ^1.6.5
  json_annotation: ^3.0.1
  moor: ^2.4.1
  social_share: ^2.0.5
  fluttertoast: ^7.0.1+1
  share: ^0.6.5+2
  flutter_search_bar: ^2.1.0
  audio_manager: ^0.5.5+3
  moor_ffi: ^0.4.0
  animator: ^1.0.0+5
  draggable_scrollbar: ^0.0.4
  yaml: ^2.2.0
  dio: ^3.0.9
  flutter_launcher_icons: ^0.7.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  google_fonts: ^1.1.0
  mobx_codegen: ^1.1.0
  built_value_generator: ^7.0.9
  json_serializable: ^3.2.5
  moor_generator: ^2.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/count_surah.png
    - assets/images/book.png
    - assets/quran-data/chapters/
    - assets/quran-data/chapters/
    - assets/quran-data/translations/
    - assets/quran-data/
    - assets/i18n/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: noorehira
      fonts:
        - asset: fonts/UthmanTN1-Ver10.otf
    - family: KFGQPC Uthman Taha Naskh
      fonts:
        - asset: fonts/UthmanTN1-Ver10.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/quran-solid.png"
